<?php
/*
 * Generated on {{$timestamp}}
 * Generated by SeedGenerator
 * Tables seeded: {{$tablesCount}}
*/

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
        Seeder main trigger method

        @return void
     */
    public function run(): void
    {
        $this->call(
            [
                {{$seederCalls}}
            ]
        );
    }
}
