<?php
/*
 * Generated on {$timestamp}
 * Generated by SeedGenerator
 * Tables seeded: {$seededTablesCount}
*/

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        \$this->call([
            {$seederCalls}
        ]);
    }
}