<?php
/*
 * Generated on {$timestamp}
 * Generated by SeedGenerator
 * Records seeded: {$this->seederRecordCount}
*/

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class {$table}Seeder extends Seeder
{
    public function run()
    {
        {$insertCommands}
    }
}
