<?php
/*
 * Generated on {{$timestamp}}
 * Generated by SeedGenerator
 * Records seeded: {{$recordCount}}
*/

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class {{$table}}Seeder extends Seeder
{
    /**
        Seeder main method

        @return void
     */
    public function run(): void
    {
        {{$insertCommands}}
    }
}
